server:
  port: 12333
spring:
  mvc:
    # 找不到匹配的请求接口时抛出异常
    throw-exception-if-no-handler-found: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: coiggahou
    password: gnn2020318
    url: jdbc:mysql://120.77.209.167:3306/aircraftwar_db
  web:
    resources:
      add-mappings: false
mybatis-plus:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.coiggahou.AircraftWar.eneity